version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: countrydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  country-api:
    build: ./country-api-service
    container_name: country-api
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/countrydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider --timeout=3 --tries=1 http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      retries: 10

    ports:
      - "8080:8080"
    networks:
      - backend
  country-ingestion:
    build: ./ingestion-service
    container_name: country-ingestion
    environment:
      COUNTRY_API_BASE_URL:  http://country-api:8080/api/v1/data/country
    depends_on:
      country-api:
        condition: service_healthy
    restart: "no" # importante: no reiniciar tras terminar
    command: ["java", "-jar", "app.jar"]
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend: